#!/usr/bin/env python
import sys
from os.path import abspath

from editorconfig_tools import EditorConfigChecker
from editorconfig import get_properties, EditorConfigError


def main(command, *args):
    checker = EditorConfigChecker()
    for filename in args:
        try:
            props = get_properties(abspath(filename))
        except EditorConfigError, e:
            print e
            continue
        else:
            for error in checker.check(filename, props):
                print "%s: %s" % (filename, error)


if __name__ == '__main__':
    main(*sys.argv)
