#!/usr/bin/env python
import sys
from os.path import abspath

from editorconfig_tools import EditorConfigFixer
from editorconfig import get_properties, EditorConfigError


def main(command, *args):
    checker = PropertyChecker()
    for filename in args:
        try:
            props = get_properties(abspath(filename))
        except EditorConfigError, e:
            print e
            continue
        else:
            checker.fix(filename, props)


if __name__ == '__main__':
    main(*sys.argv)
